name: Docker Academic_Web CI

on:
  push:
    branches: [ "DEV" ]
  pull_request:
    branches: [ "DEV" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
